protection:
  enabled: true
  max-connections-per-second: 3
  connection-timeout: 5000
  advanced:
    connection-threshold: 5
    bot-score-threshold: 10
    cleanup-interval-minutes: 15
    data-expiration-minutes: 60
    intelligent-throttling: true

notifications:
  notify-admins: true
  show-ip-addresses: true
  log-to-console: true
  log-level: WARNING

messages:
  kick-message: "§c§lConnection throttled! Please wait before reconnecting."
  admin-notification: "§c[NantiDDoS] §eBlocked connection attempt from §c{ip} §e(rate limit exceeded)"