name: nantiddos
main: id.nantiddos.Nantiddos
version: 1.0-SNAPSHOT
api-version: 1.15
commands:
  nantiddos:
    description: Main command for NantiDDoS plugin
    usage: /nantiddos [reload|status|enable|disable|clear|whitelist|blacklist|packets|dashboard]
    permission: nantiddos.admin
permissions:
  nantiddos.admin:
    description: Allows access to all NantiDDoS commands and notifications
    default: op